"""add statuses in Invited

Revision ID: 43f8fbde2bf0
Revises: 43aba459c0fd
Create Date: 2026-02-16 13:24:52.956663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f8fbde2bf0'
down_revision: Union[str, Sequence[str], None] = '43aba459c0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invited', sa.Column('kchat_status', sa.String(length=50), nullable=True))
    op.add_column('invited', sa.Column('email_status', sa.String(length=50), nullable=True))
    op.add_column('invited', sa.Column('sms_status', sa.String(length=50), nullable=True))
    op.drop_column('invited', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invited', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'invited'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('invited', 'sms_status')
    op.drop_column('invited', 'email_status')
    op.drop_column('invited', 'kchat_status')
    # ### end Alembic commands ###
