"""initial meeting_users

Revision ID: d1a1491cf31a
Revises: 
Create Date: 2026-02-07 13:10:36.564502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a1491cf31a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_users',
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('meeting_datetime', sa.DateTime(), nullable=True),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_users_email'), 'meeting_users', ['email'], unique=False)
    op.create_index(op.f('ix_meeting_users_group_id'), 'meeting_users', ['group_id'], unique=False)
    op.create_index(op.f('ix_meeting_users_meeting_datetime'), 'meeting_users', ['meeting_datetime'], unique=False)
    op.create_index(op.f('ix_meeting_users_phone'), 'meeting_users', ['phone'], unique=False)
    op.create_index(op.f('ix_meeting_users_sender_id'), 'meeting_users', ['sender_id'], unique=False)
    op.create_index(op.f('ix_meeting_users_workspace_id'), 'meeting_users', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_users_workspace_id'), table_name='meeting_users')
    op.drop_index(op.f('ix_meeting_users_sender_id'), table_name='meeting_users')
    op.drop_index(op.f('ix_meeting_users_phone'), table_name='meeting_users')
    op.drop_index(op.f('ix_meeting_users_meeting_datetime'), table_name='meeting_users')
    op.drop_index(op.f('ix_meeting_users_group_id'), table_name='meeting_users')
    op.drop_index(op.f('ix_meeting_users_email'), table_name='meeting_users')
    op.drop_table('meeting_users')
    # ### end Alembic commands ###
